/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import cms.Backend.HelperMethods;
import static cms.Backend.HelperMethods.showConfirmationDialog;
import cms.Backend.Validation;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author kenabkc
 */
public class AddCourse extends javax.swing.JFrame {

    /**
     * Creates new form AddCourse
     */
    public AddCourse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        quesNo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addCourseBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        inputCourseCode = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        inputCourseID = new javax.swing.JTextField();
        inputCourseTitle = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));

        quesNo.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        quesNo.setForeground(new java.awt.Color(51, 51, 51));
        quesNo.setText("Course");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cms/Icons/course.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Add new course");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Course ID : ");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Course Title : ");

        addCourseBtn.setBackground(new java.awt.Color(108, 99, 255));
        addCourseBtn.setForeground(new java.awt.Color(255, 255, 255));
        addCourseBtn.setText("Add Course");
        addCourseBtn.setBorder(null);
        addCourseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCourseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCourseBtnMouseClicked(evt);
            }
        });
        addCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Course Code : ");

        inputCourseCode.setForeground(new java.awt.Color(204, 204, 204));
        inputCourseCode.setText("Enter Percentage");
        inputCourseCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputCourseCodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputCourseCodeFocusLost(evt);
            }
        });
        inputCourseCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputCourseCodeMouseClicked(evt);
            }
        });
        inputCourseCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCourseCodeActionPerformed(evt);
            }
        });

        inputCourseID.setForeground(new java.awt.Color(204, 204, 204));
        inputCourseID.setText("Enter Percentage");
        inputCourseID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputCourseIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputCourseIDFocusLost(evt);
            }
        });
        inputCourseID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputCourseIDMouseClicked(evt);
            }
        });
        inputCourseID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCourseIDActionPerformed(evt);
            }
        });

        inputCourseTitle.setForeground(new java.awt.Color(204, 204, 204));
        inputCourseTitle.setText("Enter Percentage");
        inputCourseTitle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputCourseTitleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputCourseTitleFocusLost(evt);
            }
        });
        inputCourseTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputCourseTitleMouseClicked(evt);
            }
        });
        inputCourseTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCourseTitleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addCourseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(97, 97, 97)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(inputCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(inputCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(inputCourseTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(quesNo)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(quesNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(inputCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputCourseTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(addCourseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCourseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCourseBtnMouseClicked

        if (showConfirmationDialog("Do you want to add new course? ")) {

//            if (Validation.validatePercentageField(inputCourseCode.getText())) {
//                int totalPercentage = Integer.parseInt(inputCourseCode.getText());
//                
//
//                int moduleId = Account.getModuleId(modName);
//
//                int uploaded = TeacherAccount.uploadGrades(id, totalPercentage, stdPerformanceSlider.getValue(), moduleId);
//
//               
//            }
            int courseId = Integer.parseInt(inputCourseID.getText());
            String courseName = inputCourseTitle.getText();
            String courseCode = inputCourseCode.getText();

            int uploaded = AdminAccount.addCourse(courseId, courseName, courseCode);

            if (uploaded <= 0) {
                JOptionPane.showMessageDialog(null, "Error adding course.", "Add Course", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(null, "Successfully added the course.", "Add Course", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_addCourseBtnMouseClicked

    private void addCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseBtnActionPerformed

    }//GEN-LAST:event_addCourseBtnActionPerformed

    private void inputCourseCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputCourseCodeFocusGained
        // TODO add your handling code here:
        HelperMethods.handleFocusGainedLost(inputCourseCode, "Enter Percentage", new Color(158, 160, 170), evt);
    }//GEN-LAST:event_inputCourseCodeFocusGained

    private void inputCourseCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputCourseCodeFocusLost
        // TODO add your handling code here:
        HelperMethods.handleFocusGainedLost(inputCourseCode, "Enter Percentage", new Color(158, 160, 170), evt);
    }//GEN-LAST:event_inputCourseCodeFocusLost

    private void inputCourseCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputCourseCodeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCourseCodeMouseClicked

    private void inputCourseCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCourseCodeActionPerformed

    }//GEN-LAST:event_inputCourseCodeActionPerformed

    private void inputCourseIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputCourseIDFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCourseIDFocusGained

    private void inputCourseIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputCourseIDFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCourseIDFocusLost

    private void inputCourseIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputCourseIDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCourseIDMouseClicked

    private void inputCourseIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCourseIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCourseIDActionPerformed

    private void inputCourseTitleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputCourseTitleFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCourseTitleFocusGained

    private void inputCourseTitleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputCourseTitleFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCourseTitleFocusLost

    private void inputCourseTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputCourseTitleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCourseTitleMouseClicked

    private void inputCourseTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCourseTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCourseTitleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCourseBtn;
    private javax.swing.JTextField inputCourseCode;
    private javax.swing.JTextField inputCourseID;
    private javax.swing.JTextField inputCourseTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel quesNo;
    // End of variables declaration//GEN-END:variables
}
